
project_id = "nklyzlsraydlftzfjrod"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[[api.jwt_secret]]
path = "jwt-secret.txt"

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[edge_functions]
enabled = true
